# Generated by Django 4.2.1 on 2023-06-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_topic_post_topics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
