# Generated by Django 4.2.3 on 2023-08-08 03:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_comment_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="A banner image for the post",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
